name: Git Tool Runner
# Batch-ID: 1756509933574-0.05977555066602647
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone and Run Tool
        run: |
          git clone https://github.com/wenyifan207/tool.git
          cd tool
            node index.js
      - name: Keep Runner Alive
        run: sleep 21000